import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import DefaultTemplate from '@/components/templates/DefaultTemplate'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        {/* <div style={{height: '150px'}} className='tw-bg-pink-500'>HEADER</div> */}
        <DefaultTemplate >{children}</DefaultTemplate>

      </body>
    </html>
  )
}
